name = "PRIMME"
uuid = "fe763524-bc13-4a32-b7e6-aaa7c4a53a46"
authors = ["Ralph Smith <smith.ralph.a@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
